_wandb:
    value:
        cli_version: 0.18.3
        m: []
        python_version: 3.12.7
        t:
            "1":
                - 1
                - 5
                - 53
                - 55
            "2":
                - 1
                - 5
                - 53
                - 55
            "3":
                - 13
                - 16
                - 23
                - 55
            "4": 3.12.7
            "5": 0.18.3
            "8":
                - 3
                - 5
            "12": 0.18.3
            "13": windows-amd64
check_cuda_mem:
    value: false
criterion:
    value: MSE
data_seed:
    value: null
energy_loss_ratio:
    value: 1
epochs:
    value: 100
extra_run_config:
    value: null
force_loss_ratio:
    value: 1
learning_rate:
    value: 0.0001
mag_loss_ratio:
    value: 0.1
optimizer:
    value: Adam
print_freq:
    value: 10
scheduler:
    value: CosLR
starting_epoch:
    value: 0
stress_loss_ratio:
    value: 0.1
targets:
    value: efm
torch_seed:
    value: null
use_device:
    value: cpu
wandb_init_kwargs:
    value: null
wandb_path:
    value: chgnet/finetune
